version: '3.4'

volumes:
  rabbitmq_data:


services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
      RABBITMQ_DEFAULT_VHOST: my_vhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
